site_name: HES-XPLAIN
site_description: ->
  An open platform for accelerating the development of eXplainable AI systems
site_author: HES-XPLAIN
site_url: https://hes-xplain.github.io/
copyright: Copyright &copy; 2023 HES-XPLAIN
repo_url: https://github.com/HES-XPLAIN
repo_name: HES-XPLAIN
extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Platform:
    - Overview: platform/overview.md
    - Usage: platform/usage.md
    - Algorithms: platform/algos.md
  - Notebooks: notebooks.md
  - Documentation:
    - Overview: documentation/overview.md
    - Installation: documentation/installation-guide.md

    - MLxplain: 
      - Overview: documentation/mlxplain/overview.md 
      - Examples: documentation/mlxplain/examples.md

    - Rules extraction: 
      - Overview: documentation/rulesextraction/overview.md
      - Examples and Uses Cases: documentation/rulesextraction/examples.md
    
    - Dimlpfidex:
      - Overview: documentation/dimlpfidex/overview.md
      - GUI: documentation/dimlpfidex/gui.md
      - Getting started: documentation/dimlpfidex/getting-started.md
      - Fidex:
        - Overview: documentation/dimlpfidex/fidex/overview.md
        - Fidex: documentation/dimlpfidex/fidex/fidex.md
        - FidexGloRules: documentation/dimlpfidex/fidex/fidexglorules.md
        - FidexGloStats: documentation/dimlpfidex/fidex/fidexglostats.md
        - FidexGlo: documentation/dimlpfidex/fidex/fidexglo.md
      - DIMLP:
        - Overview: documentation/dimlpfidex/dimlp/overview.md
        - DimlpTrn: documentation/dimlpfidex/dimlp/dimlptrn.md
        - DimlpPred: documentation/dimlpfidex/dimlp/dimlppred.md
        - DimlpCls: documentation/dimlpfidex/dimlp/dimlpcls.md
        - DimlpRul: documentation/dimlpfidex/dimlp/dimlprul.md
        - DimlpBT: documentation/dimlpfidex/dimlp/dimlpbt.md
        - DensCls: documentation/dimlpfidex/dimlp/denscls.md
      - Training methods:
        - Overview: documentation/dimlpfidex/training-methods/overview.md
        - gradBoostTrn: documentation/dimlpfidex/training-methods/gradboosttrn.md
        - randForestsTrn: documentation/dimlpfidex/training-methods/randforeststrn.md
        - mlpTrn: documentation/dimlpfidex/training-methods/mlptrn.md
        - svmTrn: documentation/dimlpfidex/training-methods/svmtrn.md
        - computeRocCurve: documentation/dimlpfidex/training-methods/computeroccurve.md
        - normalization: documentation/dimlpfidex/training-methods/normalization.md
        - cnnTrn: documentation/dimlpfidex/training-methods/cnntrn.md
      - File formats:
        - Overview: documentation/file-formats/overview.md
        - Json: documentation/file-formats/json-configuration-files.md
        - Execution files: documentation/file-formats/execution-files.md
    - License: documentation/license.md
    - References: documentation/references.md
    - Glossary: documentation/glossary.md
    - Roadmap: documentation/roadmap.md

  - API Reference: reference.md
  - Team: team.md
#  - Resources:
#    - mkdocs.md

theme:
  name: material
  custom_dir: material
#  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  language: en
  icon:
    logo: material/brain
    repo: fontawesome/brands/github
  palette:
        # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom
      accent: custom
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      toc_depth: 2
      permalink: true

plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - social:
      cards_layout: default
#  - redirects:
#      redirect_maps:
#        'old.md': 'new.md'
#        'old/file.md': 'new/file.md'
#        'some_file.md': 'http://external.url.com/foobar'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - javascripts/tablesort.js

extra:
  generator: false
  social:
    - icon: material/github
      link: https://github.com/HES-XPLAIN
      name: HES-XPLAIN on GitHub
    - icon: material/school
      link: https://www.hes-so.ch/en/
      name: HES-SO
