site_name: MLXPLAIN
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy

extra:
  social:
    - icon: material/github
      link: https://github.com/HES-XPLAIN
      name: HES-XPLAIN on GitHub

copyright: |
  &copy; 2023 <a href="https://github.com/HES-XPLAIN" target="_blank" rel="noopener">HES-XPLAIN</a>
