site_name: HES-XPLAIN
site_description: ->
  An open platform for accelerating the development of eXplainable AI systems
site_author: HES-XPLAIN
site_url: https://hes-xplain.github.io/
copyright: Copyright &copy; 2023 HES-XPLAIN
repo_url: https://github.com/HES-XPLAIN
repo_name: HES-XPLAIN
extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - About: intro.md
  - Team: team.md
#  - Resources:
#    - mkdocs.md

theme:
  name: material
  custom_dir: material
#  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  language: en
  icon:
    logo: material/brain
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
      primary: custom
      accent: custom
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
#  - redirects:
#      redirect_maps:
#        'old.md': 'new.md'
#        'old/file.md': 'new/file.md'
#        'some_file.md': 'http://external.url.com/foobar'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - javascripts/tablesort.js

extra:
  generator: false
  social:
    - icon: material/github
      link: https://github.com/HES-XPLAIN
      name: HES-XPLAIN on GitHu
    - icon: material/school
      link: https://www.hes-so.ch/en/
      name: HES-SO
