site_name: MLXPLAIN
site_description: ->
  An open platform for accelerating the development of eXplainable AI systems
site_author: HES-XPLAIN
site_url: https://hes-xplain.github.io/
nav:
  - index.md
  - team.md
  - Resources:
    - mkdocs.md
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: cyan
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: cyan
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: material/github
      link: https://github.com/HES-XPLAIN
      name: HES-XPLAIN on GitHub

copyright: |
  &copy; 2023 <a href="https://github.com/HES-XPLAIN" target="_blank" rel="noopener">HES-XPLAIN</a>
