[tool.poetry]
name = "website"
version = "0.0.0"
description = "Website for MLxplain"
authors = ["HES-XPLAIN"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
mkdocs-material = "^9.1.8"
pillow = "^10.0.1"
cairosvg = "^2.7.0"
mkdocs-minify-plugin = "^0.6.4"
mkdocs-redirects = "^1.2.0"
mkdocs-glightbox = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
