
name: Publish

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Install Python dependencies
        run: |
          poetry run python -m pip install -U pip
          poetry install
 
      - name: Deploy
        run: |
          poetry run mkdocs gh-deploy --force
